server {
    listen 80;  # Puerto en el que Nginx escucha dentro del contenedor

    # Configuración del directorio raíz
    root /usr/share/nginx/html;  # Directorio donde están los archivos estáticos de React

    # Establece el archivo por defecto para servir
    index index.html index.htm;

    # Maneja las rutas que no están directamente en el sistema de archivos
    location / {
        try_files $uri /index.html;  # Si no encuentra el archivo, sirve index.html (para las rutas de React Router)
    }

    # Configuración para logs de acceso y error
    access_log /var/log/nginx/access.log;
    error_log /var/log/nginx/error.log;
    
    # Bloque opcional para manejar archivos grandes o configuraciones adicionales
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        expires 1y;  # Hacer caché de archivos estáticos durante 1 año
        add_header Cache-Control "public";
    }
}